module.exports = {	//	C_EVENT = calendar event
	ADD_C_EVENT:	'ADD_C_EVENT',
	REMOVE_C_EVENT:	'REMOVE_C_EVENT',
	DAYS_SCROLL_NEXT: 'DAYS_SCROLL_NEXT',
	DAYS_SCROLL_PREV:	'DAYS_SCROLL_PREV',
	CALL_FORM: 'CALL_FORM'
}